### ISSUE TITLE
Análisis de App 

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-de-la-chica-tec#1]
[Práctica 1_App con realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-de-la-chica-tec/files/10844069/Practica.1_App.con.realidad.aumentada.pdf)

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by IsraelNicolas61** [comment]
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
